### ISSUE TITLE
Integration with Home Assistant?

### ISSUE THREAD

**Issue by loriss84** [JayTongue/Pi-tmaster#1]
Hello, 
thanks for your great project.
I think an easy solution for store data in a long range time point of view is HomeAssistant.
With this integration we have already a easy and structured application.
In that i can create in  a easy way automation, trigger etc.

**Comment by JayTongue** [comment]
Hi, I looked at Home Assistant and it could be used, but that's not personally a fit for the vision I have for this project. As noted in the README.md, I wanted to stay away from IoT, especially ones that use things like custom firmware. If there are issues with the data collection over longer periods of time, I would certainly love to address that (some are already addressed in the README), since I do think it can be improved. 

If you feel like Home Assistant fits your use case, feel free to fork and change the code!
